// packages/hintphone-svelte/src/lib/HintRenderer.svelte
<!--
  Headless renderer for the current hint step: HTML content, optional image,
  and prev/next navigation — next turns into "show answer" on the last step
  of a hint with an explicit answer. Unstyled; hook into `.rk-hint*` classes.
-->
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { HintErrorReason } from './core.js';
	import { getHintphone } from './context.svelte.js';

	const DEFAULT_ERRORS: Record<HintErrorReason, string> = {
		unknown_code: '등록되지 않은 힌트 코드입니다.',
		unknown_hint: '힌트를 찾을 수 없습니다.',
		invalid_step: '해당 단계가 없습니다.',
		not_hint_device: '이 장치는 힌트 장치가 아닙니다.',
		session_not_running: '세션이 진행 중이 아닙니다.'
	};

	let {
		class: className = 'rk-hint',
		labels,
		errorLabels,
		closable = true,
		empty
	}: {
		/** Root class hook. Default 'rk-hint'. */
		class?: string;
		labels?: {
			prev?: string;
			next?: string;
			/** Next-button label on the last step when the hint has an answer. */
			showAnswer?: string;
			/** Step indicator when the answer is shown. */
			answer?: string;
			close?: string;
		};
		/** Per-reason error texts; merged over the Korean defaults. */
		errorLabels?: Partial<Record<HintErrorReason, string>>;
		/** Show a dismiss button that clears the current hint. Default true. */
		closable?: boolean;
		/** Rendered while no hint is shown (and no error). */
		empty?: Snippet;
	} = $props();

	const ctx = getHintphone();
	const hint = $derived(ctx.snapshot.hint);
	const error = $derived(ctx.snapshot.error);
</script>

{#if !hint && !error}
	{@render empty?.()}
{:else}
	<div class={className} data-answer={hint?.isAnswer || undefined}>
		{#if error}
			<p class="{className}-error" role="alert">
				{errorLabels?.[error.reason] ?? DEFAULT_ERRORS[error.reason]}
			</p>
		{/if}
		{#if hint}
			<div class="{className}-header">
				<span class="{className}-code">{hint.code}</span>
				<span class="{className}-step">
					{hint.isAnswer ? (labels?.answer ?? '정답') : `${hint.step + 1} / ${hint.stepCount}`}
				</span>
				{#if closable}
					<button type="button" class="{className}-close" onclick={() => ctx.controller?.dismiss()}>
						{labels?.close ?? '닫기'}
					</button>
				{/if}
			</div>
			<!-- Hint HTML is trusted admin input (authored in studio). -->
			<div class="{className}-body">{@html hint.textHtml}</div>
			{#if hint.imageUrl}
				<img class="{className}-image" src={hint.imageUrl} alt="" />
			{/if}
			<div class="{className}-nav">
				<button
					type="button"
					class="{className}-prev"
					disabled={!ctx.snapshot.hasPrev || ctx.snapshot.pending}
					onclick={() => ctx.controller?.prev()}
				>
					{labels?.prev ?? '이전'}
				</button>
				<button
					type="button"
					class="{className}-next"
					data-answer={ctx.snapshot.nextIsAnswer || undefined}
					disabled={!ctx.snapshot.hasNext || ctx.snapshot.pending}
					onclick={() => ctx.controller?.next()}
				>
					{ctx.snapshot.nextIsAnswer ? (labels?.showAnswer ?? '정답 보기') : (labels?.next ?? '다음')}
				</button>
			</div>
		{/if}
	</div>
{/if}

// packages/hintphone-react/src/hint-renderer.tsx
import type { ReactNode } from 'react';
import type { HintErrorReason } from '@roomkit/hintphone-core';
import { useHintphone } from './context.js';

const DEFAULT_ERRORS: Record<HintErrorReason, string> = {
  unknown_code: '등록되지 않은 힌트 코드입니다.',
  unknown_hint: '힌트를 찾을 수 없습니다.',
  invalid_step: '해당 단계가 없습니다.',
  not_hint_device: '이 장치는 힌트 장치가 아닙니다.',
  session_not_running: '세션이 진행 중이 아닙니다.',
};

export interface HintRendererProps {
  /** Root class hook. Default 'rk-hint'. */
  className?: string;
  labels?: {
    prev?: string;
    next?: string;
    /** Next-button label on the last step when the hint has an answer. */
    showAnswer?: string;
    /** Step indicator when the answer is shown. */
    answer?: string;
    close?: string;
  };
  /** Per-reason error texts; merged over the Korean defaults. */
  errorLabels?: Partial<Record<HintErrorReason, string>>;
  /** Show a dismiss button that clears the current hint. Default true. */
  closable?: boolean;
  /** Rendered while no hint is shown (and no error). Default null. */
  empty?: ReactNode;
}

/**
 * Headless renderer for the current hint step: HTML content, optional image,
 * and prev/next navigation — next turns into "show answer" on the last step
 * of a hint with an explicit answer. Unstyled; hook into `.rk-hint*` classes.
 */
export function HintRenderer({
  className = 'rk-hint',
  labels,
  errorLabels,
  closable = true,
  empty = null,
}: HintRendererProps) {
  const { controller, snapshot } = useHintphone();
  const { hint, error } = snapshot;

  if (!hint && !error) return <>{empty}</>;

  return (
    <div className={className} data-answer={hint?.isAnswer || undefined}>
      {error && (
        <p className={`${className}-error`} role="alert">
          {errorLabels?.[error.reason] ?? DEFAULT_ERRORS[error.reason]}
        </p>
      )}
      {hint && (
        <>
          <div className={`${className}-header`}>
            <span className={`${className}-code`}>{hint.code}</span>
            <span className={`${className}-step`}>
              {hint.isAnswer
                ? (labels?.answer ?? '정답')
                : `${hint.step + 1} / ${hint.stepCount}`}
            </span>
            {closable && (
              <button
                type="button"
                className={`${className}-close`}
                onClick={() => controller?.dismiss()}
              >
                {labels?.close ?? '닫기'}
              </button>
            )}
          </div>
          <div
            className={`${className}-body`}
            // Hint HTML is trusted admin input (authored in studio).
            dangerouslySetInnerHTML={{ __html: hint.textHtml }}
          />
          {hint.imageUrl && (
            <img className={`${className}-image`} src={hint.imageUrl} alt="" />
          )}
          <div className={`${className}-nav`}>
            <button
              type="button"
              className={`${className}-prev`}
              disabled={!snapshot.hasPrev || snapshot.pending}
              onClick={() => controller?.prev()}
            >
              {labels?.prev ?? '이전'}
            </button>
            <button
              type="button"
              className={`${className}-next`}
              data-answer={snapshot.nextIsAnswer || undefined}
              disabled={!snapshot.hasNext || snapshot.pending}
              onClick={() => controller?.next()}
            >
              {snapshot.nextIsAnswer
                ? (labels?.showAnswer ?? '정답 보기')
                : (labels?.next ?? '다음')}
            </button>
          </div>
        </>
      )}
    </div>
  );
}
